#!/bin/bash
echo "Pushing to origin DEV and exit 2"
git push origin dev
source ssh-config3
ssh $SSH_OPTIONS $SSH_USER@$SSH_IP -t "cd $SSH_REMOTE_FOLDER && echo 'pulling' && git pull origin dev && echo 'exitting' && exit; bash --login; "