#!/bin/bash
echo "moving to wp-content..."
cd "/var/www/html/hsoldev-homolog/wp-content"
dir
git status
git diff
echo "Adding all shortcode..."
git add --all
echo "Please enter commit description:"
read DESC 
git commit -m "$DESC"
gpr